"""Regenerate backend/certs/rds-and-public-roots.pem.

The bundle verifies Aurora's TLS certificate and must contain BOTH:

  * public Amazon roots (certifi) — this cluster's certificate is issued by
    "Amazon RSA 2048 M01", i.e. Amazon Trust Services, a public CA
  * the RDS private CAs (truststore.pki.rds.amazonaws.com) — used by other RDS
    clusters, and what a future CA rotation may switch to

Run after upgrading certifi, or if verify-full ever starts failing:

    cd backend && python scripts/refresh_ca_bundle.py
"""

import ssl
import urllib.request
from pathlib import Path

import certifi

RDS_GLOBAL = "https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem"
OUT = Path(__file__).resolve().parent.parent / "certs" / "rds-and-public-roots.pem"


def main() -> int:
    ctx = ssl.create_default_context(cafile=certifi.where())
    with urllib.request.urlopen(RDS_GLOBAL, context=ctx, timeout=30) as r:
        rds = r.read().decode()
    public = Path(certifi.where()).read_text()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "# Public Amazon roots (via certifi) + Amazon RDS CAs. Generated by\n"
        "# scripts/refresh_ca_bundle.py -- do not hand-edit.\n"
        + public + "\n" + rds
    )
    print(f"wrote {OUT} — {OUT.read_text().count('BEGIN CERTIFICATE')} certificates")
    print("Verify with: python scripts/check_db_tls.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
